### ISSUE TITLE
PageDecorator.getChild("childName")

### ISSUE THREAD

**Issue by modeckimellett** [OlsonDigital/aem-library#11]
Right now `com.day.cq.wcm.api.Page` and `com.icfolson.aem.library.api.page.PageDecorator` have `hasChild("name")` but no `getChild("name")`. I would like to see this added to `PageDecorator`.

There are a few workarounds that I've seen in use so far:
```pageDecoratorInstance.adaptTo(Resource).getChild("name").adaptTo(PageDecorator)```
(assuming `pageDecoratorInstance.hasChild("name")` comes back `true`)
or
```page.children.find { child -> child.name == "favoriteChildsName" }```
(provided by @lykorian )
or
```com.day.cq.wcm.api.PageManager.getPage(page.path + "/childName")```
(provided by @ericvangeem )

Thanks!

**Comment by markdaugherty** [comment]
Added to latest `develop` branch
