### ISSUE TITLE
AME 6.4 upgrade| aem-library snapshot version test

### ISSUE THREAD

**Issue by dibyasagar87** [OlsonDigital/aem-library#13]
Hi,

I am from Express AEM team.
I am trying to test the our code using SNAPSHOT version of aem-library from GitHub. But I am not able to build it.
I have done the below steps so far,

- Cloned the aem-library repo from github
- Built the feature-6.4 branch
- Collected all the built jars and put them in local .m2/repository/library folder structure
- Referenced them in the pom file of our code base

 
 
Then while building our codebase,  its still trying to download from the ‘http://nexus.citytech.ctmsp.com/content/groups/public’ path.

Can you please provide me the steps to carry out the test for SNAPSHOT version of aem-library in my local?

**Comment by michaelhodgdon** [comment]
What is meant by "collected all the built jars..."?  If you are installing the develop branch with "mvn clean install" all of the jars and the zip will be installed to your local repository and no more steps are needed.  Can you confirm there are no issues running that command?

**Comment by dibyasagar87** [comment]
"collected all the built jars..." means I cloned the repo in a folder in my system and ran the "mvn clean install" from that folder and got the built jars from 'target' folders.
 I have below doubts:
1. where should I clone the repo to( workspace folder of our Express codebase or out side of it )?
2. How to point to aem-library version 11.0.0-SNAPSHOT from our POM files of website, core?
 
If you can provide me the steps to make the changes will be helpful.
Thanks!

**Comment by michaelhodgdon** [comment]
The repo can be cloned anywhere on your system and should be done outside of other projects.  Then "mvn clean install" can be run within the cloned repo.  After that, you only need to update the POMs of your project to point to the snapshot version (likely in the dependency management and parent sections).

**Comment by dibyasagar87** [comment]
I am getting below error while building the project.
[ERROR] import com.icfolson.aem.library.api.components.annotations.AutoInstantiate;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import com.icfolson.aem.library.api.components cannot be resolved

is it moved to different location or AutoInstantiate is removed altogether? Please suggest how this can be fixed. We have many components using 'com.icfolson.aem.library.api.components.annotations.AutoInstantiate'

**Comment by dibyasagar87** [comment]
Hi Michael,

Do you have any update on the above issue?

Thanks!

**Comment by markdaugherty** [comment]
@dibyasagar87 support for the JSP development model was removed starting in version 10.0.0, since the Sling models/HTL component development pattern has been widely adopted.  I would recommend that you fork the 6.4-compatible branch of the project and re-add the `AutoInstantiate` class as well as any JSP tag supporting classes you may need for your components - you can copy the sources for these from version 9.2.0.  There should not be many changes to those classes required to get this working, since the underlying APIs have been stable for quite some time.

**Comment by markdaugherty** [comment]
(You may also want to consider migrating your components to HTL for future compatibility.)

**Comment by dibyasagar87** [comment]
We are using HTL for our component development.

**Comment by dibyasagar87** [comment]
Only 2-3 components were using the above annotations  AutoInstantiate class. But after I removed those from the classes. The build worked fine. So I want to know if we really need these or its ok not to use these.

**Comment by markdaugherty** [comment]
If you're using HTL, then that annotation wasn't doing anything useful since it's only relevant for JSPs.  You should be all set.

**Comment by dibyasagar87** [comment]
Ok thanks for the update.

**Comment by dibyasagar87** [comment]
I am getting errors when I am trying to load a page in 6.4. I want to show you different errors that I am getting. Are you available for a video call?

**Comment by markdaugherty** [comment]
Sorry - I don't have any availability for this beyond addressing issues here.
